### ISSUE TITLE
Improve PHP8.1 compatibility Deprecated: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated

### ISSUE THREAD

**Issue by pentium10** [rize/UriTemplate#21]
when trying to run this project on `FROM php:8.1.0beta3-apache`

<b>Deprecated</b>:  preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in <b>/var/www/html/vendor/rize/uri-template/src/Rize/UriTemplate/Parser.php</b> on line <b>22</b><br />

**Comment by rezigned** [comment]
Thanks for reporting. I'll take a look.
